server:
  servlet:
    context-path: /v1
spring:
  profiles:
    active: production
  application:
    name: "itmo-maps-server"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
logging:
  level:
    ninja.invite.api: TRACE
---

server:
  port: 8080
spring:
  profiles: dev
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/ifmomaps?useSSL=false&characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow"
    username: "ifmomaps"
    password: "ifmomaps"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

logging:
  file: server.log
  level:
    root: INFO
server:
  port: 8080
spring:
  profiles: production
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/ifmomaps?useSSL=false&characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow"
    username: "ifmomaps"
    password: "ifmomaps"